### ISSUE TITLE
Boundary and Observation Points Issue

### ISSUE THREAD

**Issue by morphed** [morphed/morphed.github.io#2]
We're having trouble with MoRPHED assigning an out-of-bounds point for both (a) boundaries and (b) discharge points. You were able to do a patch on this, but a hard fix would be great if possible going forward. Here is my email from late last night with the details:

-----------------------------------------------
The model's behaving a little bit strange, it looks like for the first flood in the series it's generating a completely empty discharge definition file ('.dis'). As such, Delft runs, but is actually doing nothing...you can see there are no messages in the output of the diag file (attached), whereas normally we're getting at least some warnings about Courant numbers.

For the second flood...the discharges are specified and Delft kicks in just fine. So I've temporarily solved this by throwing in a 'fake' flood for the first line of the hydrograph (basically just duplicating the second flood, but using an earlier time). But obviously, it's something we'll want to look into if possible? I've reproduced this bug on both my office and home computers by (a) downloading the installer exe for 0.1.2 and (b) replacing the GUTS dll with the one you just emailed over.

**Comment by khafen74** [comment]
I've got this fixed. I was calling functions to set boundaries in the wrong order so the variables determining discharge points were not correctly initialized.
